### ISSUE TITLE
Python Syntax Highlighting

### ISSUE THREAD

**Issue by ecthelionvi** [dustinblackman/oatmeal#31]
I have observed an issue with Python Syntax Highlighting where it seems Oatmeal does not seems to be able to parse comments "#" correctly. When the first comment is included in the given code, the rest of the code is commented out. As far as I can tell this seems to only be a Python issue as Go code for example worked perfectly. 

I have not configured the build.rs with a custom Python .sublime-syntax, but I am relying on bat itself. I have included a screenshot. 
![8445F589-0895-499A-BCD2-5A65765081AB_1_105_c](https://github.com/dustinblackman/oatmeal/assets/21297100/0f625e2f-bab5-4bf3-9f2d-b7ccf7a5d221)

**Comment by ecthelionvi** [comment]
I tried a different model and it works fine, so I am going to close this issue.

**Comment by dustinblackman** [comment]
Thanks for reporting!

This is a tricky one. It strictly depends on the syntax files, and the syntax highlighting library, both of which I'm using the exact same versions of both compared to Bat. I've tried messing around with changing the syntax files, but it doesn't seem to solve the issue.

I'll dig some more and see if I can figure it out.

**Comment by ecthelionvi** [comment]
I appreciate that! Thank you.

**Comment by dustinblackman** [comment]
Found it. Issue is due to how word wrapping conflicting with syntax highlighting. I have a WIP in progress that fixes it for languages I'm familiar with (Python included), but it'll likely break other stuff. 

https://github.com/dustinblackman/oatmeal/compare/main...code-comment-word-wrapping-1?expand=1

I'll likely sit on this for a bit until I can consider a better way to handle this.

**Comment by dustinblackman** [comment]
Fixed in [v0.12.1](https://github.com/dustinblackman/oatmeal/releases/tag/v0.12.1)

**Comment by ecthelionvi** [comment]
Thank you 🙏
