### ISSUE TITLE
PATH

### ISSUE THREAD

**Issue by MikeyBeez** [dustinblackman/oatmeal#34]
Thanks for writing this great software.  I found that the brew installation doesn't set the path to the oatmeal executable.  Usually brew will tell the user what path to set.  I copied oatmeal into usr/local/bin, but that might not be ideal.   Cheers!

**Comment by dustinblackman** [comment]
Thanks bud, I appreciate it!

It's been a long time since I've had brew recommend me to modify my path to install a new app. I have some memory of it only asking to do when it was a large application with a handful of binaries.

In recent versions of Homebrew, you set `eval "$(homebrew/bin/brew shellenv)"` in your shell configuration, or put `/opt/homebrew/bin` in your path where brew symlinks all binaries installed. I've tested my formula a few times every couple versions and haven't had a problem with it populating in PATH.

**Comment by MikeyBeez** [comment]
Thanks.  I've been having trouble with scrolling; so I pointed the path to /opt/homebrew/Cellar/oatmeal/0.12.1/bin/oatmeal.  Unfortunately, it didn't fix the scrolling in long oatmeal responses within neovim.  I probably have something screwed-up on my system because I make many changes everyday.

**Comment by dustinblackman** [comment]
Odd you had to do that with your PATH, as you said it may just be something custom you've setup. :)

For scrolling you have to make sure you're in insert mode within the terminal window that holds Oatmeal, then it will pickup the hot keys and do what you'd expect.

**Comment by dustinblackman** [comment]
Looks like you're all worked out. Gonna close this. Thanks!
